### ISSUE TITLE
Undead: count down available monsters

### ISSUE THREAD

**Issue by TZornG** [SteffenBauer/PocketPuzzles#13]
Hi Steffen. I got another enhancement request. Could you count down the number of available monsters shown at the top of the screen in the Undead puzzle? Maybe something like this: 

ghosts 3/5 vampires 5/5 zombies 0/7.

**Comment by SteffenBauer** [comment]
Implemented in https://github.com/SteffenBauer/PocketPuzzles/commit/7b0c015feffc7790efa934b55a08258459620b0f
