### ISSUE TITLE
Creek doesn’t check that white blocks are connected

### ISSUE THREAD

**Issue by ploum** [SteffenBauer/PocketPuzzles#14]
In the game "Creek", the logic to check whether you completed the puzzle doesn’t check for the connection between white blocks. You can "win" the game and get the message even if white blocks are not connected (they then have a dot which tells you that they are not connected)

**Comment by SteffenBauer** [comment]
Good catch, I could reproduce it. Looking into it.

**Comment by SteffenBauer** [comment]
Fixed in https://github.com/SteffenBauer/PocketPuzzles/commit/6c693eb3a8b72a7bdd10cbe5e3816bb1a94c66c0
