### ISSUE TITLE
Signpost blocks are confusing since the last update

### ISSUE THREAD

**Issue by ploum** [SteffenBauer/PocketPuzzles#15]
Since the last update, Signpost is hard to play because arrows are not greyed out from the first block of a serie.

Say you have block A, A+1, A+2. The arrow of A stay hard black which is very confusing (I re-connected several times such blocks)

**Comment by SteffenBauer** [comment]
Changed in https://github.com/SteffenBauer/PocketPuzzles/commit/6c693eb3a8b72a7bdd10cbe5e3816bb1a94c66c0

Colors should now represent more the scheme used in the original puzzle, I hope this makes the UX now better.
