### ISSUE TITLE
program segfaults with a specific sgtpuzzles.cfg

### ISSUE THREAD

**Issue by m4mmon** [SteffenBauer/PocketPuzzles#16]
Hello,
I have installed and played a little bit with 0.7.5 on a PB632 (Touch HD3).
Then suddenly the program started crashing when trying to start any game (apparently, I've tried 5 or 6).
It is possible to get the program working again by removing /mnt/ext1/system/state/sgtpuzzles.cfg.
The problematic cfg file is provided here as attachment in case the problem is investigated.
It is not completely blocking since one can get out from this situation by resetting presets but one could be annoyed losing progression.

[sgtpuzzles.zip](https://github.com/SteffenBauer/PocketPuzzles/files/6127852/sgtpuzzles.zip)

**Comment by SteffenBauer** [comment]
Thanks for catching this sneaky bug. Your second observation absolutely makes sense; the chooser buttons are not completely initialized. I now wonder why the app doesn't crash more often.

I plan some tests this week-end, hopefully releasing V 0.7.6 then.

**Comment by m4mmon** [comment]
You're welcome. In fact I took some time, traced the crash to the button_to_tapped function when calling StretchBitmap, and found the member had not been set.
It's a very little mistake in a quite big and elegant port to PB.
By the way, I love that "pearls" game.

**Comment by SteffenBauer** [comment]
Yes, I could reproduce the bug with the cfg file you provided. I observed that the encoded savegame there is quite long, looks like you played several games of _pearl_ in succession. After I initialize the inverse button bitmaps correctly to NULL, all is fine again.

I assume that the uninitialized inverse chooser buttons weren't a problem until a long savegame somehow caused byte fragments in the part of the memory heap where the uninitialized pointers were pointing to. Boom.

Thanks again, looks solved now, I will release 0.7.6 asap.

**Comment by SteffenBauer** [comment]
Hopefully solved with https://github.com/SteffenBauer/PocketPuzzles/commit/b8b286f2efc12b2a0be6a2a4ba741dd28f5df033

**Comment by m4mmon** [comment]
thank you very much
and yes I discovered pearl and now I am hooked :D
