### ISSUE TITLE
Solo (Sudoku) Bold print givens? 

### ISSUE THREAD

**Issue by Skeeve** [SteffenBauer/PocketPuzzles#19]
I just discovered, after many years of owning a PocketBook device, that there is this fantastic puzzles collection.

Thanks for that!

My question for the Sudoku is: Would it be possible to implement a bold-print of the given digits?

I also have some issues with the usability. Maybe that can be improved, but I'd like to do it on my own and contribute, if only one could get me started with a development docker container. I have no clue how to set up a development environment :(

**Comment by SteffenBauer** [comment]
Hi, great that you like the app!

Bold font for the fixed digits should be possible. It would break the API specification of the original SGT puzzle collection, which only allows FONT_VARIABLE and FONT_FIXED. But there is no reason why not introduce more fonttypes in this release, as it was already necessary to break the original API at several points.

Until then, you could try the nightly build, where I draw the fixed numbers in sudoku in a bigger font size, perhaps this is already sufficient.

**Comment by SteffenBauer** [comment]
Okay, introducing normal/bold fonts should indeed be considered. It would also be important for other games in the collection (like mathrax, unequal) with grid cells with fixed numbers.

**Comment by SteffenBauer** [comment]
Implemented by #20
