### ISSUE TITLE
Screen Refreshes

### ISSUE THREAD

**Issue by Skeeve** [SteffenBauer/PocketPuzzles#21]
Hi Steffen.

In the forum you wrote about screen refreshes. IIRC they should be ket to a minimum.

So I had this idea. Currently the notes are placed one after the other. So if you note down in a cell "3", "9", "1" and "5", you hav four refreshes:
- 3
- 39
- 139
- 1359

I propose to write each digit in a fixed position inside a cell. That way only the single digit which is placed has to be drawn.

Digit Positions:

```
_ _ _
_ _ _
_ _ _
```

So the result of the notations would be:

```
1 _ 3
_ 5 _
_ _ 9
```

Advantages:
1. Less refresh
2. One can additionally easily spot which notes are set by the digit's position

**Comment by SteffenBauer** [comment]
Implemented by 084725200aa0a38e9e2d707e180aca7f42d5f50c

**Comment by Skeeve** [comment]
Thanks a lot. Looks great.
