### ISSUE TITLE
Towers hints & selection

### ISSUE THREAD

**Issue by EastEriq** [SteffenBauer/PocketPuzzles#9]
1. tapping a hint number at the edge of the board greyes it out. Seems more a bug than an attached meaning to the color
2. it could be handy if it was possible to set a tower on a square first tapping the number and then the square

**Comment by SteffenBauer** [comment]
Thanks for the input,

1) is a feature from the official collecton that is also in several other games (Magnets, Undead). It is to denote rows/columns that the player has finished, so one can concentrate on the remaining black hints, and does not get distracted by something that is not relevant anymore. I'd like to keep this as it is, as I find it helpful.

2) This would indeed be helpful, but mean some medium rewrite in game logic. I have a similiar mechanism already included in Solo (the Sudoku version of this collection), where pressing a button without anything selected in the grid will highlight that number, and then pressing in the grid immediately fills in that number. I will keep your suggestion in mind.

**Comment by TZornG** [comment]
> 2\. [...]where pressing a button without anything selected in the grid will highlight that number that are marked in the grid, and then pressing in the grid immediately fills in that number, 

The first feature is working but the second is not when I just tested.

**Comment by SteffenBauer** [comment]
> The first feature is working but the second is not when I just tested.

Strange, I just checked, and it still works (only in Solo so far)

I implemented it as this:

1. Add some pencil marks (by pressing the '+' button in the control button bar, or by long-pressing a cell and entering possible numbers)
2. Ensure that no cells are marked now (either fully marked by short-press, or pencil-marked by long-press)
3. Press a number in the control button bar.
4. Now all cells containing that number (either with pencil marks, or full guess number) should be highlighted.
5. Now press a highlighted cell containing pencil marks. Short-pressing should fill that number. Long-pressing should remove the according pencil mark. Clicking a cell that is not highlighted will leave this highlighting mode.

Can you test if above procedure works on your device?

**Comment by TZornG** [comment]
I see. There needs to be a pencil mark present. That does work indeed. 

I had understood the cell would be filled with the pressed figure regardless of the cell's content.

**Comment by SteffenBauer** [comment]
Nr. 2) is now implemented in V0.7.0, in commit 7e15a41adaaef217bf0e6ce22aee65e4a207f206
